export declare enum EventTypeCode {
    UNDEFINED = 0,
    DEVICE_TAKEOVER = 1,
    DDOS = 2,
    UNKNOWN_MALWARE = 3,
    MAN_IN_THE_MIDDLE = 4,
    DATA_THEFT = 5,
    PORT_SCANNING = 6,
    ABNORMAL_DOWNLOAD = 7,
    ABNORMAL_INCOMING_CONNECTION = 8,
    UNSUCCESSFUL_CONNECTION_ATTEMPTS = 9,
    HIGH_VOLUME_TRANSIT = 10,
    DEVICE_LEVEL_ATTACK = 11,
    REPLAY_ATTACK = 12,
    DEVICE_TAKEOVER_ATTEMPT = 13,
    UNKNOWN_OPERATION = 14,
    CRYPTO_MINING = 15,
    SUSPICIOUS_IP = 16
}
